nome = str(input('Digite seu nome completo: '))
espaco = ''.join(nome.split())
quant = len(espaco)
priNome = nome.split()
contador = len(priNome[0])
print(nome.upper())
print(nome.lower())
print(quant)
print(contador)
